### ISSUE TITLE
Replace Allergene Lettes with Emojis

### ISSUE THREAD

**Issue by AIDude-eng** [patrickl92/GourmetClient#1]
## Idea:
The allergen abbreviation letters could be replaced with an appropriate emoji if one exists. This makes it easier to identify the allergens as no one really knows those abbreviations by hard.

## Mappings:
{"A", "🌾" },
{"B", "🦀" },
{"C", "🥚" },
{"D", "🐟" },
{"E", "🥜" },
{"F", "🥒" },
{"G", "🐮" },
{"H", "🥜🥜" },
{"L", "🥦" },
{"M", "M" },
{"N", "N" },
{"O", "🧪" },
{"P", "P" },
{"Q", "🐌" },

## Example Implementation:
![image](https://github.com/patrickl92/GourmetClient/assets/70441093/3e1c4923-a26f-45b0-a1e0-7e8022699b9c)

**Comment by patrickl92** [comment]
I think that the emojis are more confusing than the abbreviation letters. I assume that the people who are affected by allergens know the abbreviations (at least those who are affecting them). Therefore, in my opionion, this change would have a negative impact on user experience, because they need to learn new emoji abbeviations.

What could be another solution, if this information is still a requirement, is to enrich the tooltip with the names of the allergens.

**Comment by AIDude-eng** [comment]
I agree with you that this would lead to more confusion, even though the emojis are fire 🔥.  Thus this issue can be closed now. Thank you for your consideration!
